# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of MRS systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mrs_identifier }}.service"
  register: mrs_service_stat

- name: Uninstall MRS systemd services and files
  when: mrs_service_stat.stat.exists | bool
  block:
    - name: Ensure MRS systemd service is stopped
      ansible.builtin.service:
        name: "{{ mrs_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure MRS systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mrs_identifier }}.service"
        state: absent

    - name: Ensure MRS support files do not exist
      ansible.builtin.file:
        path: "{{ mrs_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels
        - config.yml

    - name: Ensure MRS image source files path does not exist
      ansible.builtin.file:
        path: "{{ mrs_container_image_self_build_src_files_path }}"
        state: absent

    - name: Ensure MRS local data path if empty
      ansible.builtin.command:
        cmd: "rmdir {{ mrs_data_path }}"
      register: mrs_data_path_deletion_result
      changed_when: mrs_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure MRS base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ mrs_base_path }}"
      register: mrs_base_path_deletion_result
      changed_when: mrs_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure MRS container network does not exist
      when: mrs_container_network_deletion_enabled
      block:
        - name: Ensure MRS container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ mrs_container_network }}"
            state: absent
          register: mrs_network_deletion_result

        - name: Ensure MRS container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ mrs_container_network }}
          register: mrs_network_deletion_result
          changed_when: mrs_container_network in mrs_network_deletion_result.stdout

- name: Check existence of MRS local data path
  ansible.builtin.stat:
    path: "{{ mrs_data_path }}"
  register: mrs_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining MRS local data path
  when: mrs_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local MRS instance has been removed, local data remains in `" + mrs_data_path + "`. Feel free to delete it."
        ]
      }}
