# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of MRS systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mrs_identifier }}.service"
  register: mrs_service_stat

- name: Uninstall MRS systemd services and files
  when: mrs_service_stat.stat.exists | bool
  block:
    - name: Ensure MRS systemd service is stopped
      ansible.builtin.service:
        name: "{{ mrs_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure MRS systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ mrs_identifier }}.service"
        state: absent

    - name: Ensure MRS container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ mrs_container_network }}"
        state: absent
      register: mrs_network_deletion_result

    - name: Ensure MRS container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ mrs_container_network }}
      register: mrs_network_deletion_result
      changed_when: mrs_container_network in mrs_network_deletion_result.stdout

    - name: Ensure MRS path does not exist
      ansible.builtin.file:
        path: "{{ mrs_base_path }}"
        state: absent
